import { DataSource } from "@/types";

// Data source badge configuration
export const getDataSourceConfig = (dataSource: DataSource) => {
  switch (dataSource) {
    case DataSource.RAPID_API_YAHOO:
    case DataSource.YAHOO_FINANCE_API:
      return {
        label: "Real",
        badge: "✅",
        bgColor: "bg-green-50",
        borderColor: "border-green-200",
        textColor: "text-green-700",
        badgeColor: "bg-green-100 text-green-700",
        description: "Real-time data from Yahoo Finance API",
      };
    
    case DataSource.CALCULATED:
      return {
        label: "Calc",
        badge: "🧮",
        bgColor: "bg-blue-50",
        borderColor: "border-blue-200", 
        textColor: "text-blue-700",
        badgeColor: "bg-blue-100 text-blue-700",
        description: "Calculated from real financial data",
      };
    
    case DataSource.ESTIMATED:
      return {
        label: "Est",
        badge: "📊",
        bgColor: "bg-yellow-50",
        borderColor: "border-yellow-200",
        textColor: "text-yellow-700",
        badgeColor: "bg-yellow-100 text-yellow-700",
        description: "Estimated based on industry standards",
      };
    
    case DataSource.AI_GENERATED:
      return {
        label: "AI",
        badge: "🤖",
        bgColor: "bg-purple-50",
        borderColor: "border-purple-200",
        textColor: "text-purple-700",
        badgeColor: "bg-purple-100 text-purple-700",
        description: "Generated by AI analysis",
      };
    
    case DataSource.MOCK:
    default:
      return {
        label: "Mock",
        badge: "🔴",
        bgColor: "bg-red-50",
        borderColor: "border-red-200",
        textColor: "text-red-700", 
        badgeColor: "bg-red-100 text-red-700",
        description: "Mock data for demonstration",
      };
  }
};

// Helper to determine if data source is real/reliable
export const isRealData = (dataSource: DataSource): boolean => {
  return [
    DataSource.RAPID_API_YAHOO,
    DataSource.YAHOO_FINANCE_API,
    DataSource.CALCULATED,
  ].includes(dataSource);
};

// Helper to get priority order of data sources (higher is better)
export const getDataSourcePriority = (dataSource: DataSource): number => {
  switch (dataSource) {
    case DataSource.RAPID_API_YAHOO:
    case DataSource.YAHOO_FINANCE_API:
      return 5;
    case DataSource.CALCULATED:
      return 4;
    case DataSource.ESTIMATED:
      return 3;
    case DataSource.AI_GENERATED:
      return 2;
    case DataSource.MOCK:
    default:
      return 1;
  }
};

// Data quality indicator
export const getDataQualityIndicator = (dataSource: DataSource) => {
  const priority = getDataSourcePriority(dataSource);
  
  if (priority >= 4) {
    return { level: "High", color: "text-green-600", icon: "📈" };
  } else if (priority >= 3) {
    return { level: "Medium", color: "text-yellow-600", icon: "📊" };
  } else {
    return { level: "Low", color: "text-red-600", icon: "📉" };
  }
};